---
abstract: 'Barcode Writer in Pure PostScript'
author:
  - 'Lars Dɪᴇᴄᴋᴏᴡ C<< <daxim@cpan.org> >>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35_02
  perl: 5.010
generated_by: 'Module::Build version 0.351'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-BWIPP
provides:
  Alien::BWIPP:
    file: lib/Alien/BWIPP.pm
    version: 0.001
requires:
  English: 1.04
  File::ShareDir: 1.01
  IO::File: 1.14
  Moose: 0.93
  Moose::Meta::Class: 0.93
  MooseX::ClassAttribute: 0.10
  Storable: 2.21
  perl: 5.010
resources:
  bugtracker: http://github.com/daxim/Alien-BWIPP/issues
  license: http://www.opensource.org/licenses/mit-license.php
  repository: http://github.com/daxim/Alien-BWIPP
version: 0.001
