---
abstract: 'Barcode Writer in Pure PostScript'
author:
  - "Lars DÉªá´\x87á´\x84á´\x8Bá´\x8Fá´¡ C<< <daxim@cpan.org> >>"
  - 'Matthew Newton C<< <mcnewton@cpan.org> >>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: 0.35_14
  perl: '5.010'
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.141520'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-BWIPP
provides:
  Alien::BWIPP:
    file: lib/Alien/BWIPP.pm
    version: '0.007'
requires:
  English: '1.04'
  File::ShareDir: '1.01'
  IO::File: '1.14'
  Moose: '0.93'
  Moose::Meta::Class: '0.93'
  MooseX::ClassAttribute: '0.10'
  Storable: '2.21'
  perl: '5.010'
resources:
  bugtracker: http://github.com/daxim/Alien-BWIPP/issues
  license: http://opensource.org/licenses/mit-license.php
  repository: http://github.com/daxim/Alien-BWIPP
version: '0.007'
